# Generated by Django 2.0.7 on 2018-08-06 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180803_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='状态名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '回访状态',
                'verbose_name_plural': '回访状态',
            },
        ),
        migrations.CreateModel(
            name='StatusOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='状态值')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ReviewStatus', verbose_name='状态')),
            ],
            options={
                'verbose_name': '状态选项',
                'verbose_name_plural': '状态选项',
            },
        ),
    ]
